# Global Configuration
global:
  proxy: null  # 将从 secrets.yaml 加载

# Input Configuration
input:
  directory: "data"
  formats: [".mp4", ".mkv", ".webm", ".m4a", ".mp3", ".wav"]
  specific_files: []

# Output Configuration
output:
  directory: "data"
  formats: ["json", "srt", "txt"]
  verbose: true
  # SRT 输出选项
  srt_options:
    max_line_width: 80   # 每行最大字符数
    max_line_count: 1    # 每个字幕最大行数
    highlight_words: false

# Model Configuration
model:
  # Whisper model settings
  whisper:
    name: "large-v3"  # 支持的模型: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium,
                      # large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en
    device: "cpu"
    compute_type: "int8"  # float16, int8
    batch_size: 8
    model_dir: "models"  # local path to save models

  # Alignment model settings
  aligner:
    enabled: true
    language: "en"  # auto-detect if null

  # Diarization settings
  diarization:
    enabled: false
    auth_token: null  # 将从 secrets.yaml 加载
    min_speakers: 1
    max_speakers: 2

# Transcription Parameters
transcription:
  word_timestamps: true
  return_char_alignments: false
